---
parameters_ga:
  population_size: 500
  franciosite: 25.0
  losers_franciosite: 25.0
  franciosite_diminution_by_generation: 3.5
  mutation_rate: 1.2
  crossover_rate: 0.5
  elitisme: False
  number_of_elitisme: 40
  generation: 3 # nombre generation, 0 pour désactiver
  etalon: False
  losers: True
  number_of_losers: 25
  reseed: False
  number_of_reseeds: 5
  number_of_children: 2
  selection_method: "tournament" # "tournament", "wheel", "rank"
---
parameters_eda:
  population_size: 500
  franciosite: 15.0
  selection_ratio: 0.5
  learning_rate: 0.1
---
parameters_general:
  number_of_iterations: 25
  number_of_words_to_generate: 1000
  output_file: "mutat.csv"
