---
parameters_ga:
  population_size: 50
  franciosite: 20.0
  franciosite_diminution_by_generation: 10
  mutation_rate: 1.2
  crossover_rate: 0.5
  elitisme: 0 # nombre generation, 0 pour désactiver
  etalon: False
  losers: False
  number_of_losers: 10
  reseed: False
  number_of_reseeds: 5
  number_of_children: 1
---
parameters_eda:
  population_size: 50
  franciosite: 20.0
  selection_ratio: 0.5
  learning_rate: 0.1
---
parameters_general:
  number_of_iterations: 20
  number_of_words_to_generate: 50
  output_file: "words.csv"
